/*
  This is a Class Library for an Adapter for the P2WDB OrbitDB.
*/

class P2WDB {
  constructor (localConfig = {}) {
    // Encapsulate dependencies
    this.orbitdb = localConfig.orbitdb
  }

  // Insert a new entry into the database.
  // Returns the hash generated by OrbitDB for the new entry.
  async insert (entry) {
    try {
      // Add the entry to the Oribit DB
      const hash = await this.orbitdb.put(entry.key, entry.value)
      console.log('hash: ', hash)

      return hash
    } catch (err) {
      console.error('Error in p2wdb.js/insert()')
      throw err
    }
  }
}

module.exports = P2WDB
